version: "3"
services:
  curl:
    image: byrnedo/alpine-curl
    command: cat
    networks:
      - compose
  pass:
    image: nginx
    volumes:
      - "${PWD:-.}/pass.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - compose
  auth:
    image: nginx
    volumes:
      - "${PWD:-.}/auth.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - compose
networks:
  compose:
